name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test on ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [18, 20, 21]

    steps:
      - uses: actions/checkout@v5

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: npm run lint

      - name: Run coverage
        run: npm run coverage
